---
ci:
  skip: [terraform_docs, terraform_fmt, terraform-validate, tflint, terragrunt-hclfmt]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-merge-conflict
      - id: no-commit-to-branch
      - id: check-yaml
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.19
    hooks:
      - id: terragrunt-hclfmt
      - id: terraform-validate
        files: ^examples/
      - id: tflint
        files: ^examples/
        exclude: .*/README\.md
      - id: gofmt
        files: ^test/
      - id: golint
        files: ^test/
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
